//!AUTH

// export const USER_LOADED = 'USER_LOADED';
export const LOGIN_SUCCES = 'LOGIN_SUCCES';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const COMPANY_SIGN_UP_SUCCESS = 'COMPANY_SIGN_UP_SUCCESS';
export const COMPANY_SIGN_UP_FAIL = 'COMPANY_SIGN_UP_FAIL';
export const LOGOUT = ' LOGOUT';
// export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS';
// export const SIGN_UP_FAIL = 'SIGN_UP_FAIL';
// export const LOAD_USER = 'LOAD_USER';
// export const LOAD_USER_ERROR = 'LOAD_USER_ERROR';

//!Additional data
//company
export const GET_COMPANY_TYPES_SUCCESS = 'GET_COMPANY_TYPES_SUCCESS';
export const GET_COMPANY_TYPES_FAIL = 'GET_COMPANY_TYPES_FAIL';
//countries-cities
export const GET_ALL_COUNTRIES_SUCCESS = 'GET_ALL_COUNTRIES_SUCCESS';
export const GET_ALL_COUNTRIES_FAIL = 'GET_ALL_COUNTRIES_FAIL';
export const GET_CITIES_BY_COUNTRY_ID_SUCCESS =
  'GET_CITIES_BY_COUNTRY_ID_SUCCESS';
export const GET_CITIES_BY_COUNTRY_ID_FAIL = 'GET_CITIES_BY_COUNTRY_ID_FAIL';
//transport
export const GET_TRANSPORT_TYPES_SUCCESS = 'GET_TRANSPORT_TYPES_SUCCESS';
export const GET_TRANSPORT_TYPES_FAIL = 'GET_TRANSPORT_TYPES_FAIL';
export const GET_SUB_TRANSPORT_TYPES_SUCCESS =
  'GET_SUB_TRANSPORT_TYPES_SUCCESS';
export const GET_SUB_TRANSPORT_TYPES_FAIL = 'GET_SUB_TRANSPORT_TYPES_FAIL';
//payment
export const GET_PAYMENT_TYPES_SUCCESS = 'GET_PEYMENT_TYPES_SUCCESS';
export const GET_PAYMENT_TYPES_FAIL = 'GET_PEYMENT_TYPES_FAIL';

export const GET_CURRENCY_TYPES_SUCCESS = 'GET_CURRENCY_TYPES_SUCCESS';
export const GET_CURRENCY_TYPES_FAIL = 'GET_CURRENCY_TYPES_FAIL';

// ! Working Data

export const GET_FILTERED_CARGO_POSTS_SUCCESS =
  'GET_FILTERED_CARGO_POSTS_SUCCESS';
export const GET_FILTERED_CARGO_POSTS_FAIL = 'GET_FILTERED_CARGO_POSTS_FAIL';
