//AUTH

// export const USER_LOADED = 'USER_LOADED';
export const LOGIN_SUCCES = 'LOGIN_SUCCES';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const COMPANY_SIGN_UP_SUCCESS = 'COMPANY_SIGN_UP_SUCCESS';
export const COMPANY_SIGN_UP_FAIL = 'COMPANY_SIGN_UP_FAIL';
// export const LOGOUT = ' LOGOUT';
// export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS';
// export const SIGN_UP_FAIL = 'SIGN_UP_FAIL';
// export const LOAD_USER = 'LOAD_USER';
// export const LOAD_USER_ERROR = 'LOAD_USER_ERROR';

//Additional data
export const GET_COMPANY_TYPES_SUCCESS = 'GET_COMPANY_TYPES_SUCCESS';
export const GET_COMPANY_TYPES_FAIL = 'GET_COMPANY_TYPES_FAIL';
export const GET_ALL_COUNTRIES_SUCCESS = 'GET_ALL_COUNTRIES_SUCCESS';
export const GET_ALL_COUNTRIES_FAIL = 'GET_ALL_COUNTRIES_FAIL';
export const GET_CITIES_BY_COUNTRY_ID_SUCCESS =
  'GET_CITIES_BY_COUNTRY_ID_SUCCESS';
export const GET_CITIES_BY_COUNTRY_ID_FAIL = 'GET_CITIES_BY_COUNTRY_ID_FAIL';
