//!AUTH

// export const USER_LOADED = 'USER_LOADED';
export const LOGIN_SUCCES = 'LOGIN_SUCCES';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const COMPANY_SIGN_UP_SUCCESS = 'COMPANY_SIGN_UP_SUCCESS';
export const PERSON_SIGN_UP_SUCCESS = 'PERSON_SIGN_UP_SUCCESS';
export const COMPANY_SIGN_UP_FAIL = 'COMPANY_SIGN_UP_FAIL';
export const PERSON_SIGN_UP_FAIL = 'PERSON_SIGN_UP_FAIL';
export const GET_PROFILE_SUCCESS = 'GET_PROFILE_SUCCESS';
export const GET_PROFILE_FAIL = 'GET_PROFILE_FAIL';
export const LOGOUT = ' LOGOUT';
// export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS';
// export const SIGN_UP_FAIL = 'SIGN_UP_FAIL';
// export const LOAD_USER = 'LOAD_USER';
// export const LOAD_USER_ERROR = 'LOAD_USER_ERROR';

//!Additional data
//company
export const GET_COMPANY_TYPES_SUCCESS = 'GET_COMPANY_TYPES_SUCCESS';
export const GET_COMPANY_TYPES_FAIL = 'GET_COMPANY_TYPES_FAIL';

//transport
export const GET_TRANSPORT_TYPES_SUCCESS = 'GET_TRANSPORT_TYPES_SUCCESS';
export const GET_TRANSPORT_TYPES_FAIL = 'GET_TRANSPORT_TYPES_FAIL';
export const GET_TRANSPORT_SUB_TYPES_SUCCESS =
  'GET_TRANSPORT_SUB_TYPES_SUCCESS';
export const GET_TRANSPORT_SUB_TYPES_FAIL = 'GET_TRANSPORT_SUB_TYPES_FAIL';
//payment
export const GET_PAYMENT_TYPES_SUCCESS = 'GET_PEYMENT_TYPES_SUCCESS';
export const GET_PAYMENT_TYPES_FAIL = 'GET_PEYMENT_TYPES_FAIL';

export const GET_CURRENCY_TYPES_SUCCESS = 'GET_CURRENCY_TYPES_SUCCESS';
export const GET_CURRENCY_TYPES_FAIL = 'GET_CURRENCY_TYPES_FAIL';

//documents
export const GET_DOCUMENTS_SUCCESS = 'GET_DOCUMENTS_SUCCESS';
export const GET_DOCUMENTS_FAIL = 'GET_DOCUMENTS_FAIL';

//loading conditions
export const GET_LOADING_CONDITIONS_SUCCESS = 'GET_LOADING_CONDITIONS_SUCCESS';
export const GET_LOADING_CONDITIONS_FAIL = 'GET_LOADING_CONDITIONS_FAIL';

//transport conditions
export const GET_TRANSPORT_CONDITIONS_SUCCESS =
  'GET_TRANSPORT_CONDITIONS_SUCCESS';
export const GET_TRANSPORT_CONDITIONS_FAIL = 'GET_TRANSPORT_CONDITIONS_FAIL';

//freight conditions
export const GET_FREIGHT_CONDITIONS_SUCCESS = 'GET_FREIGHT_CONDITIONS_SUCCESS';
export const GET_FREIGHT_CONDITIONS_FAIL = 'GET_FREIGHT_CONDITIONS_FAIL';

//! Add Posts

export const ADD_CARGO_POSTS_SUCCESS = 'ADD_CARGO_POSTS_SUCCESS';
export const ADD_CARGO_POSTS_FAIL = 'ADD_CARGO_POSTS_FAIL';

//!Transit Store

export const SAVE_START_END_PLACES = 'SAVE_START_END_PLACES';
export const SAVE_CARGO_POST_ADDITIONAL_DATA =
  'SAVE_CARGO_POST_ADDITIONAL_DATA';
export const REMOVE_TRANSIT_DATA = 'REMOVE_TRANSIT_DATA';

export const ITEMS_QUANTITY = 'ITEMS_QUANTITY';

//! ProfileFavorites

//cargo favorites

export const GET_ALL_CARGO_FAVORITES_SUCCESS =
  'GET_ALL_CARGO_FAVORITES_SUCCESS';
export const GET_ALL_CARGO_FAVORITES_FAIL = 'GET_ALL_CARGO_FAVORITES_FAIL ';

export const ADD_ITEM_TO_CARGO_FAVORITES_SUCCESS =
  'ADD_ITEM_TO_CARGO_FAVORITES_SUCCESS';
export const ADD_ITEM_TO_CARGO_FAVORITES_FAIL =
  'ADD_ITEM_TO_CARGO_FAVORITES_FAIL';

export const REMOVE_ITEM_FROM_CARGO_FAVORITES_SUCCESS =
  'REMOVE_ITEM_FROM_CARGO_FAVORITES_SUCCESS';
export const REMOVE_ITEM_FROM_CARGO_FAVORITES_FAIL =
  'REMOVE_ITEM_FROM_CARGO_FAVORITES_FAIL';
